# Generated by Django 4.1.3 on 2022-12-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('songurl', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100)),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('song', models.ManyToManyField(to='room.song')),
            ],
        ),
    ]
